name: Release

on:
  release:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Docker build
      run: docker build -t latest ./
      
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: hfarah
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push container
      run: docker push hfarah/csi5112lec5:latest
