name: Release

on:
  release:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Docker build
      run: docker build -t latest ./csi5112w22service/
      
    - name: Docker login
      run: docker login -u hfarah --password ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push container
      run: docker push hfarah/csi5112lec5:latest
